version: '3.7'
networks:
  docker_network:
services:
  PHP-SRV:
    image: php-imagick
    container_name: php-imagick
    volumes:
      - .:/var/www/html
      - ./../../configs/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      #- ~/work/docker/ex3/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - docker_network 
    ports: 
      - '8080:80'
  